#!/bin/bash

sqlite3 $FEED_DATABASE > feed.dot <<SQL
select 'graph FEED { overlap=true; layout=neato; nodesep=1; sep=1; maxiter=500; '
union all
select distinct
       nid
    || ' [ margin=' || margin
    || coalesce(' label="' || title || '"','')
    || coalesce(' URL="' || uri || '"','')
    || ' color=transparent shape=plaintext fontsize=12 ];'
  from vgraphnodes
union all
select nid1 || ' -- ' || nid2 || ' [ '|| attributes || ' ];'
  from vegraphedges
union all
select '}'
;
SQL

dot -Tsvg -ofeed.svg feed.dot
